# Generated by Django 3.0.6 on 2020-06-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='doi',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='paper',
            name='isbn',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='paper',
            name='issn',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='paper',
            name='pages',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='paper',
            name='publishing_company',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='paper',
            name='site',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='paper',
            name='type_paper',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='created_on',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='eprint',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='paper',
            name='pdf',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='paper',
            name='picture',
            field=models.URLField(default=None),
        ),
    ]
