# Generated by Django 3.0.6 on 2020-06-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_api', '0002_auto_20200605_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
