# Generated by Django 3.0.6 on 2020-06-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_api', '0004_auto_20200605_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='year',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='paper',
            name='created_on',
            field=models.DateField(default=None),
        ),
    ]
