# Generated by Django 3.0.6 on 2020-06-05 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_api', '0005_auto_20200605_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
