# Generated by Django 3.0.6 on 2020-06-05 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_api', '0006_auto_20200605_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='created_on',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='doi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='eprint',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='isbn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='issn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='pages',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='pdf',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='picture',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='publishing_company',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='paper',
            name='site',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
